title: LIT.
email: itlundby@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  IT Consultancy & Software Solutions.
baseurl: "/lundby" # the subpath of your site, e.g. /blog
url: "https://itlundby.github.io" # the base hostname & protocol for your site, e.g. http://example.com
language: "en"
languages:
  en: "English"
  da: "Danish"
about:
  name: 
    en: Lundby IT
    da: Lundby IT
  role:
    en: IT Consultancy and Solutions
    da: IT Konsulent
  description: 
    en: Aarhus Based Developer.
    da: Konsulenthus i Aarhus.
skills:
  - .NET
  - SQL
  - Go
  - Python
  - Docker
  - React
  - Angular
  - Team Lead
  - Architecture
  - Problem Solving
  - Communication
  - HTML
  - CSS
  - Git
projects:
  - name: "Developer in Fintech"
    description: "Software developer in Danish Fintech for four years."
    stack:
      - ".NET"
      - "SQL"
      - "Angular"
      - "Go"
      - "Docker"
  - name: "IT Consultant"
    description: "A software developer for a Danish Consultancy for a year."
    stack:
      - ".NET"
      - "Python"
      - "MicroPython"
      - "React"
      - "TypeScript"
      - "Docker"
      - "Azure"
  - name: "Senior Developer and Lead"
    description: "A senior developer and team lead, in a global Danish company."
    stack:
      - ".NET"
      - "SQL"
      - "Azure"
      - "Docker"
  - name: "Solutions Architect"
    description: "A solutions architect."
    stack:
      - ".NET"
      - "SQL"
      - "Google Cloud"
      - "Azure"
      - "Docker"
      - "Clean Architecture"
      - "Domain Driven Design"

# Build settings
theme: minima
plugins:
  - jekyll-feed